name-template: 'v$RESOLVED_VERSION 🌈'

tag-template: 'v$RESOLVED_VERSION'

template: |
  ## Changes

  $CHANGES

  $CONTRIBUTORS

categories:
  - title: '💣 Breaking Change'
    labels:
      - "change"
      - "breaking"
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'improvement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'refactor'
      - 'security'
  - title: '📗 Docs'
    labels:
      - 'documentation'
  - title: '🧪 Tests'
    labels:
      - "tests"
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'change'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'chore'
      - 'dependencies'
      - 'documentation'
      - 'maintenance'
      - 'refactor'
      - 'tests'
  default: patch

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'breaking'
    branch:
      - '/break.*/'
      - '/breaking.*/'
  - label: 'documentation'
    files:
      - '**/*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/docs\/.+/'
      - '/docs.*/'
  - label: 'tests'
    branch:
      - '/tests\/.+/'
      - '/tests.*/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - 'chore.*'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
      - '/fix.*/'
      - '/bugfix.*/'
      - '/bug.*/'
      - '/hot.*/'
      - '/hotfix.*/'
      - '/sec.*/'
      - '/security.*/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
      - '/feature.*/'
      - '/feat.*/'
      - '/improvement.*/'
    title:
      - '/feat/i'
  - label: 'dependencies'
    #files:
      #- 'go.mod'
      #- 'go.sum'
      #- 'vendor*'
    branch:
      - '/deps\/.+/'
      - '/dependabot.*/'

filter-by-commitish: true
