name: Release Drafter & Autolabeler

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - master

jobs:
  Autolabeler_Pull_Requests:
    if: github.event_name == 'pull_request'
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
      - name: Pull Requests Autolabeler
        uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Create_or_Update_Release_Draft:
    if: github.event_name == 'push'
    runs-on: [ self-hosted, ubuntu-latest ]
    steps:
      - name: Create/Update Release Drafter
        uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
