name: Releases Notifier
on:
  release:
    types: [ released ]
jobs:
  post-msteams-release:
    uses: pagonxt/workflows/.github/workflows/release-notifier-v1.yml@main
    secrets:
      app_id: ${{ secrets.DEPENDENCIES_APP_ID }}
      private_key: ${{ secrets.DEPENDENCIES_PRIVATE_KEY }}
