name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: simple-service
  ANCHORE: true
  # TODO: Uncomment that you need
  ##### AKS #####
  # CLOUD: aks
  # TODO: Uncomment and insert your data to deploy in azure
  #AKS_RESOURCE_GROUP: insert-resource-group
  #AKS_CLUSTER_NAME: insert-cluster-name
  #AKS_NAMESPACE: insert-namespace
  
  ##### EKS #####
  # CLOUD: eks
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build and test project
      run: mvn -B --file pom.xml clean verify
    - uses: ashley-taylor/junit-report-annotations-action@master
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
      if: always()
    - id: getfilename
      run: echo "::set-output name=file::$(ls build/*.jar)"
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: artifact
        path: target/${{ steps.getfilename.outputs.file }}



