# Scan your code with SonarQube to detects Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
#
# Read more details about this workflow at https://github.com/SonarSource/sonarqube-scan-action
# Read more information on how to analyze your code at https://docs.sonarqube.org/latest/analysis/github-integration/
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    # Get projectVersion. This is an example for Nodejs, adapt it to your needs and language
    - name: Get project variables
      id: vars
      run: |
        VERSION=`node -p "require('./package').version"`
        echo "::set-output name=version::$VERSION"
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectVersion=${{ steps.vars.outputs.version}}
          -Dsonar.links.ci=${{ github.server_url }}/${{ github.repository }}/actions
          -Dsonar.links.scm=${{ github.server_url }}/${{ github.repository }}
          -Dsonar.links.issue=${{ github.server_url }}/${{ github.repository }}/issues
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
